config/routes.rb
YoPrevengo::Application.routes.draw do
  
  resources :users
  resources :user_sessions
  resources :user_types

  resources :matrix_headers
  resources :risk_matrices   
  resources :preventive_procedures  
  resources :risks_damages
  resources :criteria_types
  resources :activity_types
  resources :damages

  resources :companies do
    resources :work_areas  
    resources :evaluation_criteries
  end  

  resources :work_areas do 
      resources :work_flows
  end   

  resources :work_flows do 
    resources :activities
  end

  resources :activities do
    resources :unitary_tasks
  end

  resources :dangers do
    resources :risks
  end 
  
  
  get "welcome/index"

  match 'listar' => 'unitary_tasks#list', as: :listar

  match 'login' => 'user_sessions#new', as: :login
  match 'logout' => 'user_sessions#destroy', as: :logout
  match 'asignarRol/:id' => 'users#asignarRol', :as => :asignarRol

  match 'new_matriz/:id' => 'matrix_headers#new_matriz', as: :new_matriz
  match 'borrar_cabecera/:id' => 'matrix_headers#borrar_cabecera', as: :borrar_cabecera
  match 'generar_nueva_matriz/:id' => 'risk_matrices#generar_nueva_matriz', as: :generar_nueva_matriz

  match 'asignar/:id/asignar' => 'matrix_headers#asignar', as: :asignar
  match 'quitar_riesgo/:id/' => 'matrix_headers#quitar_riesgo', as: :quitar_riesgo

  match 'generar_matriz/:id' => 'risk_matrices#generar_matriz', as: :generar_matriz  
  match 'actualizar_riesgo_evaluado/:id' => 'risk_matrices#actualizar_riesgo_evaluado', as: :actualizar_riesgo_evaluado
  match 'ver_matriz/:id' => 'risk_matrices#ver_matriz', as: :ver_matriz

  match 'generar_procedimiento/:id' => 'preventive_procedures#generar_procedimiento', as: :generar_procedimiento
  match 'ver_procedimiento/:id' => 'preventive_procedures#ver_procedimiento', as: :ver_procedimiento
  match 'actualizar_procedimiento/:id' => 'preventive_procedures#actualizar_procedimiento', as: :actualizar_procedimiento

  match 'users/:id/actualizar_datos' => 'users#actualizar_datos', as: :actualizar_datos
  match 'editarpassword/:id/edit_password' => 'users#edit_password', as: :edit_password
  match 'update_password/:id' => 'users#update_password', as: :update_password

  root :to => 'welcome#index'
  

  match ':controller(/:action(/:id))(.:format)'
end

app/models/damage.rb
class Damage < ActiveRecord::Base
	attr_accessible :description
	has_many :risks_damages
	has_many :risk, :through => :risks_damages
end

app/models/unitary_task.rb
class UnitaryTask < ActiveRecord::Base
	attr_accessible :description, :activity_id, :risk_ids, :generate
	
	# Relaciones
	belongs_to :activity
	has_many :matrix_headers

	# Validaciones
	# Descripcion de la tarea unitaria
	validates 	:description, :presence => { :message => "Debe ingresar una tarea unitaria" }

end

app/controllers/unitary_tasks_controller.rb
class UnitaryTasksController < ApplicationController
  # GET /unitary_tasks
  # GET /unitary_tasks.json
  def index
    @unitary_tasks = UnitaryTask.all
     @activity = Activity.find(params[:activity_id])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @unitary_tasks }
    end
  end
  def list    
    @riesgos = Risk.all
    @riesgo = 0
    @riesgoarray = Array.new
    @tarea = UnitaryTask.find(params[:id])

    respond_to do |format|
      format.html # list.html.erb
      format.json { render json: @unitary_task }
    end
  end
  # GET /unitary_tasks/1
  # GET /unitary_tasks/1.json
  def show
    @i = 1
    @headers = MatrixHeader.where(:unitary_task_id => params[:id])
    @unitary_task = UnitaryTask.find(params[:id])
    @activity = Activity.find(params[:activity_id])
    @work_flow = WorkFlow.find(@activity.work_flow_id)
    @company = Company.find(@work_flow.work_area.company_id)
       
    @probabilidad = EvaluationCritery.where(:company_id => @company.id , :criteria_type_id => 2).order(:criteria_type_id)
    @consecuencia = EvaluationCritery.where(:company_id => @company.id , :criteria_type_id => 1).order(:criteria_type_id)
    @max = @consecuencia.last.value

    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @unitary_task }
    end
  end

  # GET /unitary_tasks/new
  # GET /unitary_tasks/new.json
  def new
    @boton = "Agregar"
    @unitary_task = UnitaryTask.new
    @activity = Activity.find(params[:activity_id])
    @work_flow = WorkFlow.find(@activity.work_flow_id)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @unitary_task }
    end
  end

  # GET /unitary_tasks/1/edit
  def edit
    @boton = "Actualizar"
    @unitary_task = UnitaryTask.find(params[:id])
    @activity = Activity.find(params[:activity_id])
    @work_flow = WorkFlow.find(@activity.work_flow_id)
  end

  # POST /unitary_tasks
  # POST /unitary_tasks.json
  def create
    @activity = Activity.find(params[:activity_id])
    @unitary_task = @activity.unitary_tasks.new(params[:unitary_task])
    @work_flow = WorkFlow.find(@activity.work_flow_id)

    respond_to do |format|
      if @unitary_task.save
        format.html { redirect_to [@work_flow, @activity], notice: 'se creo exitosamente.' }
        format.json { render json: @unitary_task, status: :created, location: @unitary_task }
      else
        format.html { render action: "new" }
        format.json { render json: @unitary_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /unitary_tasks/1
  # PUT /unitary_tasks/1.json
  def update
    @unitary_task = UnitaryTask.find(params[:id])
    @activity = Activity.find(params[:activity_id])
    @work_flow = WorkFlow.find(@activity.work_flow_id)

    respond_to do |format|
      if @unitary_task.update_attributes(params[:unitary_task])
        format.html { redirect_to [@activity, @unitary_task], notice: 'se modifico exitosamente.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @unitary_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /unitary_tasks/1
  # DELETE /unitary_tasks/1.json
  def destroy
    @unitary_task = UnitaryTask.find(params[:id])
    @activity = Activity.find(params[:activity_id])
    @work_flow = WorkFlow.find(@activity.work_flow_id)

    @unitary_task.destroy

    respond_to do |format|
      format.html { redirect_to [@work_flow,@activity] }
      format.json { head :no_content }
    end
  end


end

app/helpers/unitary_tasks_helper.rb
module UnitaryTasksHelper
end

app/views/unitary_tasks/_form.html.erb
<div class="well">

  <%= simple_form_for [@activity, @unitary_task] do |f| %>
    <% if @unitary_task.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@unitary_task.errors.count, "error") %> prohibited this unitary_task from being saved:</h2>

        <ul>
        <% @unitary_task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :'Nombre de la Tarea' %><br />
      <%= f.text_field :description, :class => "input-medium search-query", style: "width:400px"  %>
    </div>

    <div class="modal-footer">
      <center>
        <% if @boton == 'Agregar'%>
          <div class="actions">
            <button type="submit" class="btn btn-success">
              <i class="icon-ok"> Agregar</i>
            </button>
            <i>
              <%= link_to ' Atrás', work_flow_activity_path(@work_flow.id, @activity.id), :class => "icon-arrow-left btn" %>
            </i>
        <% else %>    
          <div class="actions">
            <button type="submit" class="btn btn-warning"> 
              <i class="icon-refresh"> Actualizar</i>
            </button>
            <button class="btn" data-dismiss="modal" aria-hidden="true">Cancelar</button>
        <% end %>
      </center>
    </div>

  <% end %>
</div>

app/views/unitary_tasks/_formasignar.html.erb
<%= form_tag :action =>'guardarasignar' do %>
<h3 align="center">Tarea Unitaria: <%= @unitary_task.description %></h3>
</br></br>

<div class="field" align="center">
	<table align="center" class="table table-condensed table-striped">
		<tr><td colspan="2" align='center'><h4>Riesgos asignables</h4></tr>
		<%= hidden_field_tag "unitary_task[risk_ids][]", nil  %>
	
	
		<% Risk.all.each do |risk| %>
		
		<tr>
			<td><%= check_box_tag "unitary_task[risk_ids][]", risk.id , @unitary_task.risk_ids.include?(risk.id) %></td>
		 
			<td><%= label_tag dom_id(risk), risk.description%></td>
		</tr>
		<%end%>
	</table>
</div>

<div class= "actions">
	<%= hidden_field_tag :tarea_id, @unitary_task.id  %>
	<%= submit_tag @boton, :class => "btn btn-success"%>
</div>	
<%end %>

app/views/unitary_tasks/asignar.html.erb
<%= render 'formasignar' %>

app/views/unitary_tasks/edit.html.erb
<h3 align="center">Actualizando tarea unitaria</h3>

<%= render 'form' %>

<%= link_to 'Atras', activity_unitary_task_path(@activity.id, @unitary_task.id), :class => "btn btn-warning"%>

app/views/unitary_tasks/index.html.erb
<h3 align="center">Listando las Tareas Unitarias</h3>

<table class='table table' >
  <tr>
    <th>ID</th>
    <th>Descripción</th>
    <th>Actividad</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @unitary_tasks.each do |unitary_task| %>
  <tr>
    <td><%= unitary_task.id %></td>
    <td><%= unitary_task.description %></td>
    <td><%= unitary_task.activity_id %></td>
    <td><%= link_to 'Ver', activity_unitary_task_path(@activity, unitary_task.id) %></td>
    <td><%= link_to 'Editar', edit_activity_unitary_task_path(@activity, unitary_task) %></td>
    <td><%= link_to 'Eliminar', activity_unitary_task_path(@activity, unitary_task.id), confirm: 'Esta seguro?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nueva Tarea Unitaria', new_activity_unitary_task_path %>

app/views/unitary_tasks/list.html.erb
<h2>Nombre Tarea <%= @tarea.id %></h2>
<h1>Selecciones los riesgos aplican para la tarea unitaria</h1>
<table class='table table'>
  <tr>
    <th>Peligros</th>
    <th></th>
    <th>Riesgos</th>
    <th></th>
    <th></th>
  </tr>

<% @riesgos.each do |risk| %>
  <tr>
    <% if @riesgo != risk.danger_id %>
    <% @riesgo = risk.danger_id %>
    <td><%= risk.danger.description%></td>
	<td><%= check_box_tag "@riesgoarray", risk.id%></td>    
    <td><%= risk.id %>-<%= risk.description%></td>
    <%else%>
    <td><%= %></td>
    <td><%= check_box_tag "@riesgoarray", risk.id%></td>
    <td><%= risk.id %>-<%= risk.description%></td>
    <%end%>
   </tr>
<% end %>
</table>

<ul>
<% @riesgoarray.each do |ra| %>  
  <li><%= ra.id %></li>
<%end %>  

</ul>

app/views/unitary_tasks/new.html.erb
<h3 align="center">Agregar Tarea Unitaria</h3>

<%= render 'form' %>
<!--
<%= link_to 'Atras', work_flow_activity_path(@work_flow.id, @activity.id), :class => "btn btn-warning"%>
-->

app/views/unitary_tasks/show.html.erb
<p id="notice"><%= notice %></p>
<div class="well span3" id="divtabla3">
	<p>
    	<b><h4 align="center">Datos de la Tarea Unitaria</h4></b>
  	</p>

	<p>
		<b>Compañía:</b>
		<%= @unitary_task.activity.work_flow.work_area.company.name %>
	</p>
	<p>
		<b>Área de Trabajo:</b>
		<%= @unitary_task.activity.work_flow.work_area.name %>
	</p>
	<p>
		<b>Proceso de Trabajo:</b>
		<%= @unitary_task.activity.work_flow.name %>
	</p>
	<p>
		<b>Actividad :</b>
		<%= @unitary_task.activity.description %>

	</p>
	<p>
	  <b>Tarea Unitaria :</b>
	  <%= @unitary_task.description %>
	</p>

<!--
	<%= link_to ' Atrás', work_flow_activity_path(@work_flow, @unitary_task.activity_id), :class => "icon-arrow-left btn"%></br>
-->
	<div>
	    <a href="#myModal" role="button" class="icon-refresh btn btn-warning" data-toggle="modal"> Actualizar Tarea Unitaria</a>
	    <div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
	        <h3 id="myModalLabel">Actualizar Tarea Unitaria</h3>
	      </div>
	      <div class="modal-body">
	        <p>
	          <%= render 'form' %>
	        </p>
	      </div>
	    </div>
		| <%= link_to ' Atrás', work_flow_activity_path(@work_flow, @unitary_task.activity_id), :class => "icon-arrow-left btn" %></br>
	</div>
</div>

<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
<center>
	<div id="divtabla421">
<%= link_to ' Generar Nueva Matriz',new_matriz_path(@unitary_task), :class => "active icon-pencil btn btn-info" %>
	</div>
</center>
<div class="well span6" id="divtabla44">

<% if @headers.count !=0 %>
	<b><h4 align="center">Matrices de riesgo</h4></b>
	
	<table class="table" >
	<tr>
		<th>N° Matriz</th>
		<th>Fecha creación</th>
		<th>Última actualización</th>
		<th></th>
	</tr>
	<% @headers.each do |mh|%>
	<tr align="center">
		<td><%= @i %></td>
		<td><%= mh.created_at.day %>/<%= mh.created_at.month %>/<%= mh.created_at.year %></td>
		<td><%= mh.updated_at.day %>/<%= mh.updated_at.month %>/<%= mh.updated_at.year %></td>
		<td width="20"><%= link_to ' Ver',matrix_header_path(mh.id), :class => "active btn btn-info" %>
		<%@i += 1%>	
	</tr>
	<% end %>
	</table>
<%else%>
<center>No hay matrices registradas</center>
<%end%>

</div>