config/routes.rb
YoPrevengo::Application.routes.draw do
  
  resources :users
  resources :user_sessions
  resources :user_types

  resources :matrix_headers
  resources :risk_matrices   
  resources :preventive_procedures  
  resources :risks_damages
  resources :criteria_types
  resources :activity_types
  resources :damages

  resources :companies do
    resources :work_areas  
    resources :evaluation_criteries
  end  

  resources :work_areas do 
      resources :work_flows
  end   

  resources :work_flows do 
    resources :activities
  end

  resources :activities do
    resources :unitary_tasks
  end

  resources :dangers do
    resources :risks
  end 
  
  
  get "welcome/index"

  match 'listar' => 'unitary_tasks#list', as: :listar

  match 'login' => 'user_sessions#new', as: :login
  match 'logout' => 'user_sessions#destroy', as: :logout
  match 'asignarRol/:id' => 'users#asignarRol', :as => :asignarRol

  match 'new_matriz/:id' => 'matrix_headers#new_matriz', as: :new_matriz
  match 'borrar_cabecera/:id' => 'matrix_headers#borrar_cabecera', as: :borrar_cabecera
  match 'generar_nueva_matriz/:id' => 'risk_matrices#generar_nueva_matriz', as: :generar_nueva_matriz

  match 'asignar/:id/asignar' => 'matrix_headers#asignar', as: :asignar
  match 'quitar_riesgo/:id/' => 'matrix_headers#quitar_riesgo', as: :quitar_riesgo

  match 'generar_matriz/:id' => 'risk_matrices#generar_matriz', as: :generar_matriz  
  match 'actualizar_riesgo_evaluado/:id' => 'risk_matrices#actualizar_riesgo_evaluado', as: :actualizar_riesgo_evaluado
  match 'ver_matriz/:id' => 'risk_matrices#ver_matriz', as: :ver_matriz

  match 'generar_procedimiento/:id' => 'preventive_procedures#generar_procedimiento', as: :generar_procedimiento
  match 'ver_procedimiento/:id' => 'preventive_procedures#ver_procedimiento', as: :ver_procedimiento
  match 'actualizar_procedimiento/:id' => 'preventive_procedures#actualizar_procedimiento', as: :actualizar_procedimiento

  match 'users/:id/actualizar_datos' => 'users#actualizar_datos', as: :actualizar_datos
  match 'editarpassword/:id/edit_password' => 'users#edit_password', as: :edit_password
  match 'update_password/:id' => 'users#update_password', as: :update_password

  root :to => 'welcome#index'
  

  match ':controller(/:action(/:id))(.:format)'
end

app/models/company.rb
class Company < ActiveRecord::Base
	attr_accessible :name, :address, :company_type
	
	# Relaciones
	has_many :work_areas, :dependent => :destroy
	has_many :evaluation_criteries

	# Validaciones
	# Nombre de la Compañia
	validates 	:name, :presence => { :message => "Debe ingresar un nombre" }
	
 	# Direccion
	validates 	:address, :presence => { :message => "Debe ingresar una direccion" }
 	
 	# Giro de la Compañia			
 	validates 	:company_type, :presence => { :message => "Debe ingresar una direccion" }
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @companies }
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @areas = WorkArea.where(:company_id => params[:id])
    @criterio = EvaluationCritery.where(:company_id => params[:id])
    @company = Company.find(params[:id])
    $company = Company.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/new
  # GET /companies/new.json
  def new
    @boton = "Agregar"
    @company = Company.new


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/1/edit
  def edit
    @boton = "Actualizar"
    @company = Company.find(params[:id])
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(params[:company])

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: "Se creo exitosamente." }
        format.json { render json: @company, status: :created, location: @company }
      else
        format.html { render action: "new" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /companies/1
  # PUT /companies/1.json
  def update
    @company = Company.find(params[:id])

    respond_to do |format|
      if @company.update_attributes(params[:company])
        format.html { redirect_to @company, notice: 'Se modifico exitosamente.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<div class="well">

<!--<div class="well" id="divtabla2">-->
  <%= form_for(@company) do |f| %>
    <% if @company.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

        <ul>
        <% @company.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :'Nombre de la compañía' %>
      <%= f.text_field :name, :class => "input-medium search-query", style: "width:400px"  %>
    </div>
    <br />
    <div class="field" >
      <%= f.label :'Dirección de la compañía' %>
      <%= f.text_field :address, :class => "input-medium search-query", style: "width:400px" %>
    </div>
    <br />
    <div class="field">
      <%= f.label :'Giro o Actividad Económica' %>
      <%= f.text_field :company_type, :class => "input-medium search-query", style: "width:400px" %>
    </div>
    <br />
    

    <div class="modal-footer">
      <center>
        <% if @boton == 'Agregar'%>
          <div class="actions">
          <button type="submit" class="btn btn-success">
             <i class="icon-ok"> Agregar</i>
          </button>
          
          <i>
            | <%= link_to ' Atrás', companies_path, :class => "icon-arrow-left btn btn-middle" %>
          </i>
        <%  else %>    
          <div class="actions">
            <button type="submit" class="btn btn-warning"> 
              <i class="icon-refresh"> Actualizar</i>
            </button>
            <%= @boton %>
            |<button class="btn" data-dismiss="modal" aria-hidden="true">Cancelar</button>
            <!--<%= link_to ' Atras', companies_path, :class => "icon-arrow-left btn btn-middle" %>-->
        <% end %>
      </center>
    </div>

    
<% end %>

</div>

app/views/companies/edit.html.erb
<h2 align="center">Actualizar Compañía</h2>

<%= render 'form' %>
<!--
<%= link_to ' Atras', company_path(@company), :class => "icon-arrow-left btn" %>
-->

app/views/companies/index.html.erb
<h3 align="center">Listado de Compañías</h3>
<center>
  <table>
    <tr>
      <%= link_to ' Agregar Compañia', new_company_path, :class => "active btn icon-pencil btn-success" %>
    </tr>
  </table>
</center>

<div class="well span6" id="divtabla">
  <table class='table'>
    <tr>
      <!--<th>ID</th>-->
      <th>Nombre de la Empresa</th>
      <th></th>
    </tr>

    <% @companies.each do |company| %>
      <tr>
        <!--<td><%= company.id %></td>-->
        <td><%= link_to company.name, company %>
        <td><%= link_to ' Eliminar', company, confirm: "¿Estas seguro que desea eliminar la compañia: #{company.name}", method: :delete, :class => "active icon-trash btn btn-mini btn-danger" %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/companies/new.html.erb
<h3 align="center">Agregar Compañía</h3>

<%= render 'form' %>
<!--
<%= link_to ' Atras', companies_path, :class => "icon-arrow-left btn btn-middle" %>
-->

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>


<!--Datos de Empresa-->

<div class="well span3" id="divtabla3">
	<p>
		<b><h4 align="center">Datos de la Compañía</h4></b>
	</p>

	<p>
		<b>Nombre de la Compañía:</b>
		<%= @company.name %>
	</p>

	<p>
		<b>Direccion de la Compañía:</b>
		<%= @company.address %>
	</p>

	<p>
		<b>Giro de la Compañía:</b>
		<%= @company.company_type %>
	</p>
<!--
	<%= link_to ' Actualizar Compañía', edit_company_path(@company), :class => "active icon-refresh btn btn-warning" %>
		<%= link_to ' Atras', companies_path, :class => "icon-arrow-left btn" %>
-->
<div>
		<a href="#myModal" role="button" class="icon-refresh btn btn-warning" data-toggle="modal"> Actualizar Compañía</a>
		<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
				<h3 id="myModalLabel">Actualizar Compañía</h3>
			</div>
			<div class="modal-body">
				<p>
					<%= render 'form' %>
				</p>
			</div>
		</div>
			| <%= link_to ' Atrás', companies_path, :class => "icon-arrow-left btn" %>
	</div>


</div>

<!--criterios-->

<!--

<div class="well span3" id="divtabla4"> 
	<p>
		<b><h4 align="center">Criterios de Evaluación</h4></b>
	</p>
	<ul>
		<% @criterio.each do |c| %>
		
			<li>
				<%= link_to c.name, company_evaluation_critery_path(@company, c.id) %>
			</li>
		<% end %>
	</ul>

	<%= link_to ' Agregar Criterio', new_company_evaluation_critery_path(@company.id), :class => "active icon-pencil btn btn-success" %>

</div> -->

<!--areas de trabajo-->

<!--

<div class="well span6" id="divtabla5">
	<p>
		<b><h4 align="center">Listado de Áreas de Trabajo</h4></b>
	</p>
	<table class='table'>
		<tr>
			<th>Areas de trabajo</th>
			<th></th>
		</tr>

		<% @areas.each do |areas| %>
			<tr>
				
				<td><%= link_to areas.name, company_work_area_path(@company,areas.id) %>
				<td><%= link_to ' Eliminar', company_work_area_path(@company, areas), confirm: "¿Esta seguro que desea eliminar el area de trabajo: #{@company.name}?", method: :delete, :class => " icon-trash btn btn-mini btn-danger" %></td>
			</tr>
		<% end %>
	</table>
	
		 <%= link_to ' Agregar Area de Trabajo', new_company_work_area_path(@company.id), :class => "active icon-pencil btn btn-success" %>
		
</div> -->
<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>

<div class="tabbable"> <!-- Only required for left/right tabs -->
	<ul class="nav nav-tabs">
		<li ><a href="#tab1" data-toggle="tab">Criterios de Evaluación</a></li>
		<li><a href="#tab2" data-toggle="tab">Listado de Áreas de Trabajo</a></li>
	</ul>
	<div class="tab-content">
		<div class="tab-pane " id="tab1">
			<p>


				<div> 
					<p>
						<b><h4 align="center">Criterios de Evaluación</h4></b>
					</p>
						 <div class="well" id="divtabla8">
						<table class='table table-condensed'>
							<tr>
								<td><h5>Probabilidad</h5></td>
								<td><h5>Valor</h5></td>
								<td></td>
							</tr>
								
							<% @criterio.each do |c| %>
								<tr>

								<% if c.criteria_type_id == 1%>        
									<td><%= link_to c.name, company_evaluation_critery_path(@company, c.id) %></td>
									<td><%= link_to c.value, company_evaluation_critery_path(@company, c.id) %></td>
									<!--<td><%= link_to c.criteria_type_id, company_evaluation_critery_path(@company, c.id) %></td>-->
									<td><%= link_to ' Eliminar', company_evaluation_critery_path(@company, c.id), confirm: "¿Esta seguro que desea eliminar el criterio de probabilidad: #{c.name}?", method: :delete, :class => " icon-trash btn btn-mini btn-danger active" %></td>
								<% end %>
							</tr>
							<% end %>
						</table>
						<center>
							<%= link_to ' Agregar probabilidad', new_company_evaluation_critery_path(@company.id, :x => 'probabilidad'), :class => "active icon-pencil btn btn-success" %>
						</center>
						</div>
						

						



						<div class="well" id="divtabla9">
						<table class='table table-condensed'>
							<tr>
								<td><h5>Consecuencia</h5></td>
								<td><h5>Valor</h5></td>
								<td></td>							
							</tr>
								
							<% @criterio.each do |c| %>
								<tr>

								<% if c.criteria_type_id == 2%>        
									<td><%= link_to c.name, company_evaluation_critery_path(@company, c.id) %></td>
									<td><%= link_to c.value, company_evaluation_critery_path(@company, c.id) %></td>
									<!--<td><%= link_to c.criteria_type_id, company_evaluation_critery_path(@company, c.id) %></td>-->
									<td><%= link_to ' Eliminar', company_evaluation_critery_path(@company, c.id), confirm: "¿Esta seguro que desea eliminar el criterio de evaluacion: #{c.name}?", method: :delete, :class => " icon-trash btn btn-mini btn-danger active" %></td>
								<% end %>
							</tr>
							<% end %>
						</table>
						<center>
							<%= link_to ' Agregar consecuencia', new_company_evaluation_critery_path(@company.id, :x => 'consecuencia'), :class => "active icon-pencil btn btn-success" %>
						</center>
						</div>
					

				</div>



			</p>
		</div>
		<div class="tab-pane" id="tab2">
			<p>
				<div class="well span6" id="divtabla8">
					<p>
						<b><h4 align="center">Listado de Áreas de Trabajo</h4></b>
					</p>
					<table class='table'>
						<tr>
							<th>Áreas de trabajo</th>
							<th></th>
						</tr>

						<% @areas.each do |areas| %>
							<tr>
								
								<td><%= link_to areas.name, company_work_area_path(@company,areas.id) %>
								<td><%= link_to ' Eliminar', company_work_area_path(@company, areas), confirm: "¿Esta seguro que desea eliminar el area de trabajo: #{@company.name}?", method: :delete, :class => "active icon-trash btn btn-mini btn-danger" %></td>
							</tr>
						<% end %>
					</table>
					
						 <%= link_to ' Agregar Área de Trabajo', new_company_work_area_path(@company.id), :class => "active icon-pencil btn btn-success" %>
						
				</div>

			</p>
		</div>
	</div>
</div>