config/routes.rb
YoPrevengo::Application.routes.draw do
  
  resources :users
  resources :user_sessions
  resources :user_types

  resources :matrix_headers
  resources :risk_matrices   
  resources :preventive_procedures  
  resources :risks_damages
  resources :criteria_types
  resources :activity_types
  resources :damages

  resources :companies do
    resources :work_areas  
    resources :evaluation_criteries
  end  

  resources :work_areas do 
      resources :work_flows
  end   

  resources :work_flows do 
    resources :activities
  end

  resources :activities do
    resources :unitary_tasks
  end

  resources :dangers do
    resources :risks
  end 
  
  
  get "welcome/index"

  match 'listar' => 'unitary_tasks#list', as: :listar

  match 'login' => 'user_sessions#new', as: :login
  match 'logout' => 'user_sessions#destroy', as: :logout
  match 'asignarRol/:id' => 'users#asignarRol', :as => :asignarRol

  match 'new_matriz/:id' => 'matrix_headers#new_matriz', as: :new_matriz
  match 'borrar_cabecera/:id' => 'matrix_headers#borrar_cabecera', as: :borrar_cabecera
  match 'generar_nueva_matriz/:id' => 'risk_matrices#generar_nueva_matriz', as: :generar_nueva_matriz

  match 'asignar/:id/asignar' => 'matrix_headers#asignar', as: :asignar
  match 'quitar_riesgo/:id/' => 'matrix_headers#quitar_riesgo', as: :quitar_riesgo

  match 'generar_matriz/:id' => 'risk_matrices#generar_matriz', as: :generar_matriz  
  match 'actualizar_riesgo_evaluado/:id' => 'risk_matrices#actualizar_riesgo_evaluado', as: :actualizar_riesgo_evaluado
  match 'ver_matriz/:id' => 'risk_matrices#ver_matriz', as: :ver_matriz

  match 'generar_procedimiento/:id' => 'preventive_procedures#generar_procedimiento', as: :generar_procedimiento
  match 'ver_procedimiento/:id' => 'preventive_procedures#ver_procedimiento', as: :ver_procedimiento
  match 'actualizar_procedimiento/:id' => 'preventive_procedures#actualizar_procedimiento', as: :actualizar_procedimiento

  match 'users/:id/actualizar_datos' => 'users#actualizar_datos', as: :actualizar_datos
  match 'editarpassword/:id/edit_password' => 'users#edit_password', as: :edit_password
  match 'update_password/:id' => 'users#update_password', as: :update_password

  root :to => 'welcome#index'
  

  match ':controller(/:action(/:id))(.:format)'
end

app/models/damage.rb
class Damage < ActiveRecord::Base
	attr_accessible :description
	has_many :risks_damages
	has_many :risk, :through => :risks_damages
end

app/models/matrix_header.rb
class MatrixHeader < ActiveRecord::Base
	attr_accessible :unitary_task_id , :risk_ids
	has_many :risk_matrices
	has_many :risks, :through => :risk_matrices
	belongs_to :unitary_task
end

app/controllers/matrix_headers_controller.rb
class MatrixHeadersController < ApplicationController
  # GET /matrix_headers
  # GET /matrix_headers.json
  def index
    @matrix_headers = MatrixHeader.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @matrix_headers }
    end
  end

  # GET /matrix_headers/1
  # GET /matrix_headers/1.json
  def show
    @header = MatrixHeader.find(params[:id])
    @unitary_task = UnitaryTask.find(@header.unitary_task_id)
    @activity = Activity.find(@unitary_task.activity_id)
    @risk_matrix = RiskMatrix.where(:matrix_header_id => @header.id)
    @company = Company.find(@unitary_task.activity.work_flow.work_area.company_id)
    @evaluation_critery = EvaluationCritery.where(:company_id => @company.id)
    @probabilidad = EvaluationCritery.where(:company_id => @company.id , :criteria_type_id => 2).order(:criteria_type_id)
    @consecuencia = EvaluationCritery.where(:company_id => @company.id , :criteria_type_id => 1).order(:criteria_type_id)
    
    
    # obtener rango de criticidad con numeros repetidos
    @r = []
    @probabilidad.each do |p|      
      @consecuencia.each do |c|
        @r << p.value * c.value
      end  
    end
    # eliminar los numeros rangos repetidos
    @r = @r.uniq 

    # obtener riesgos evaluados y riesgos no evaluados
    @evaluado = []
    @noevaluado = []
    @matrixx = RiskMatrix.where(:matrix_header_id => @header.id)
    @matrixx.each do |m|
     if m.generate == true
      @evaluado << m
      else
       @noevaluado << m
      end
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @matrix_header }
     
      format.html
      format.pdf do
        pdf = MatrixHeaderPdf.new(@header,@risk_matrix)
        send_data pdf.render, filename: "matrix_header_#{@header.id}.pdf",
                              type: "application/pdf",
                              disposition: "inline"
      end
    end
  end

  # GET /matrix_headers/new
  # GET /matrix_headers/new.json
  def new
    @matrix_header = MatrixHeader.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @matrix_header }
    end
  end

  # GET /matrix_headers/1/edit
  def edit
    @matrix_header = MatrixHeader.find(params[:id])
  end

  # POST /matrix_headers
  # POST /matrix_headers.json
  def create
    @matrix_header = MatrixHeader.new(params[:matrix_header])

    respond_to do |format|
      if @matrix_header.save
        format.html { redirect_to @matrix_header, notice: 'Matrix header was successfully created.' }
        format.json { render json: @matrix_header, status: :created, location: @matrix_header }
      else
        format.html { render action: "new" }
        format.json { render json: @matrix_header.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /matrix_headers/1
  # PUT /matrix_headers/1.json
  def update
    @matrix_header = MatrixHeader.find(params[:id])

    respond_to do |format|
      if @matrix_header.update_attributes(params[:matrix_header])
        format.html { redirect_to @matrix_header, notice: 'Matrix header was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @matrix_header.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matrix_headers/1
  # DELETE /matrix_headers/1.json
  def destroy
    @matrix_header = MatrixHeader.find(params[:id])
    @matrix_header.destroy

    respond_to do |format|
      format.html { redirect_to matrix_headers_url }
      format.json { head :no_content }
    end
  end


  def new_matriz
    @boton = "Asignar Riesgos a nueva matriz"
    @unitary_task = UnitaryTask.find(params[:id])
    @activity = Activity.find(@unitary_task.activity_id)
    @work_flow = WorkFlow.find(@activity.work_flow_id)
    @header = MatrixHeader.new(:unitary_task_id => @unitary_task.id)
    @header.save
  end

  def borrar_cabecera    
    @header = MatrixHeader.find(params[:id])
    @unitary_task = UnitaryTask.find(@header.unitary_task_id)
    @activity = Activity.find(@unitary_task.activity_id)
    @header.destroy

    respond_to do |format|
      format.html { redirect_to [@activity,@unitary_task] }
      format.json { head :no_content }
    end
  end

  def guardar_new_matriz      
    params[:matrix_header][:risk_ids] ||= []
    @unitary_task = UnitaryTask.find(params[:tarea_id])
    @header = MatrixHeader.find(params[:header_id])
    @activity = Activity.find(@unitary_task.activity_id)
    @work_flow = WorkFlow.find(@activity.work_flow_id)


    respond_to do |format|
      if @header.update_attributes(params[:matrix_header])
        @matrices = RiskMatrix.where(:matrix_header_id => params[:header_id], :generate => nil )
        @matrices.each do |r|
          @matriz = RiskMatrix.find(r.id)
          @matriz.generate = false
          @matriz.save
        end
        format.html { redirect_to generar_nueva_matriz_path(@header.id), notice: 'se modifico exitosamente.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @unitary_task.errors, status: :unprocessable_entity }
      end
    end
  end

  def asignar
    @boton = "Asignar Riesgos"
    @header = MatrixHeader.find(params[:id])
    @unitary_task = UnitaryTask.find(@header.unitary_task_id)
    @activity = Activity.find(@unitary_task.activity_id)
    @work_flow = WorkFlow.find(@activity.work_flow_id)
  end

  def guardarasignar   
    params[:matrix_header][:risk_ids] ||= []
    @unitary_task = UnitaryTask.find(params[:tarea_id])
    @header = MatrixHeader.find(params[:header_id])
    @activity = Activity.find(@unitary_task.activity_id)
    @work_flow = WorkFlow.find(@activity.work_flow_id)


    respond_to do |format| 
      if @header.update_attributes(params[:matrix_header])
        @matrices = RiskMatrix.where(:matrix_header_id => params[:header_id], :generate => nil )
        @matrices.each do |r|
          @matriz = RiskMatrix.find(r.id)
          @matriz.generate = false
          @matriz.save
        end
        format.html { redirect_to matrix_header_path(@header.id), notice: 'se modifico exitosamente.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @unitary_task.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/helpers/matrix_headers_helper.rb
module MatrixHeadersHelper
end

app/views/matrix_headers/_form.html.erb
<%= form_for(@matrix_header) do |f| %>
  <% if @matrix_header.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@matrix_header.errors.count, "error") %> prohibited this matrix_header from being saved:</h2>

      <ul>
      <% @matrix_header.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :unitary_task_id %><br />
    <%= f.number_field :unitary_task_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/matrix_headers/_form_nueva_matriz.html.erb
<%= form_tag :action =>'guardar_new_matriz' do %>
<h5 align="center">Tarea Unitaria: <%= @unitary_task.description %></h5>
</br></br>

<div class="field" align="center">
	<table align="center" class="table table-condensed table-striped">
		<tr><td colspan="2" align='center'><h4>Riesgos asignables</h4></tr>
		<%= hidden_field_tag "matrix_header[risk_ids][]", nil  %>
		
		<% Risk.all.each do |risk| %>		
		<tr>
			<td><%= check_box_tag "matrix_header[risk_ids][]", risk.id , @header.risk_ids.include?(risk.id) %></td>
		 	<td><%= label_tag dom_id(risk), risk.description%></td>
		</tr>
		<%end%>
	</table>
</div>

<div class= "actions">
	<%= hidden_field_tag :tarea_id, @unitary_task.id  %>
	<%= hidden_field_tag :header_id, @header.id  %>
	<%= submit_tag @boton, :class => "btn btn-success"%>
</div>	
<%end %>

app/views/matrix_headers/_formasignar.html.erb
<%= form_tag :action =>'guardarasignar' do %>
<h3 align="center">Tarea Unitaria: <%= @unitary_task.description %></h3>
</br></br>

<div class="field" align="center">
	<table align="center" class="table table-condensed table-striped">
		<tr><td colspan="2" align='center'><h4>Riesgos asignables</h4></tr>
		<%= hidden_field_tag "matrix_header[risk_ids][]", nil  %>
	
	
		<% Risk.all.each do |risk| %>
		
		<tr>
		 	<td><%= check_box_tag "matrix_header[risk_ids][]", risk.id , @header.risk_ids.include?(risk.id) %></td>
		 	<td><%= label_tag dom_id(risk), risk.description%></td>
		</tr>
		<%end%>
	</table>
</div>

<div class= "actions">
	<%= hidden_field_tag :tarea_id, @unitary_task.id  %>
	<%= hidden_field_tag :header_id, @header.id  %>
	<%= submit_tag @boton, :class => "btn btn-success"%>
</div>	
<%end %>

app/views/matrix_headers/asignar.html.erb
<%= render 'formasignar' %>

app/views/matrix_headers/edit.html.erb
<h1>Editing matrix_header</h1>

<%= render 'form' %>

<%= link_to 'Show', @matrix_header %> |
<%= link_to 'Back', matrix_headers_path %>

app/views/matrix_headers/index.html.erb
<h1>Listing matrix_headers</h1>

<table>
  <tr>
    <th>Unitary task</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @matrix_headers.each do |matrix_header| %>
  <tr>
    <td><%= matrix_header.unitary_task_id %></td>
    <td><%= link_to 'Show', matrix_header %></td>
    <td><%= link_to 'Edit', edit_matrix_header_path(matrix_header) %></td>
    <td><%= link_to 'Destroy', matrix_header, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Matrix header', new_matrix_header_path %>

app/views/matrix_headers/new.html.erb
<h1>New matrix_header</h1>

<%= render 'form' %>

<%= link_to 'Back', matrix_headers_path %>

app/views/matrix_headers/new_matriz.html.erb
<h3 align="center">Asignar riesgos a nueva matriz</h3>
<%= render 'form_nueva_matriz' %>
<%= link_to 'Atras', activity_unitary_task_path(@activity,@unitary_task.id), :class => "btn btn-warning" %>

app/views/matrix_headers/show.html.erb
<center>
    <p>
        <h3>Matriz de Riesgos</h3>
    </p>
    <p>
        <b>Compañia: </b><%= @company.name%>
    </p>
     <p>
        <b>Tarea Unitaria: </b><%= @unitary_task.description %>
     </p>
</center>


 <center>
    <button type="button" class="icon-flag btn btn-info" data-toggle="collapse" data-target="#demo">
        Ver Riesgos Evaluados
    </button>
</center>
<br/>

<div id="demo" class="collapse ">
    <center>
        <div class="well span5" id="divtabla10">
            <% @cont=1%>
            <% if @evaluado.count != 0 %>
                <table class="table">
                    <tr>
                        <td><b>N°</b></td>
                        <td><b>Riesgo<b></td>
                    </tr>
                    <% @evaluado.each do |e|%>
                        <tr>
                            <td><%=@cont %></td>
                            <!--<td><%=e.risk_id%></td>--> 
                            <td align="center"><%= e.risk.description%></td>
                            <% @cont=@cont+1   %>
                        </tr>   
                    <%end%>
                </table>
            <%end%>
        </div>
    </center>
</div>

<center>
    <div class="well span5" id="divtabla10">
        
        <% @con=1%>
        <% if @noevaluado.count != 0 %>
            <table class="table">
                <tr><b>Riesgos No Evaluados</b></tr>
                <tr>
                    <td width="25"><b>N°</b></td>
                    <td><b>Riesgo<b></td>
                </tr>                
                <% @noevaluado.each do |e|%>
                    <tr>
                        <td><%=@con %></td>
                        <!--<td><%=e.risk_id%></td>--> 
                        <td align="center"><%= e.risk.description%></td>
                    </tr>
                    <% @con+=1   %>   
                <%end%>
            </table>
        <%end%>
    
        <%= link_to 'Asignar Riesgo', asignar_path(@header), :class => "active btn btn-primary" %>

        <% if @noevaluado.count != 0 %>
            <%= link_to 'Incorporar a la Matriz',generar_matriz_path(@header), :class => "active btn btn-success" %></br></br> 
        <%end%>

    </div>
</center>

<center>
    <table border="1" class="table-condensed">
            <tr>
                <td><b>Compañía</b></td>
                <td colspan="8"><%= @company.name%></td>
            </tr>
            <tr>
                <td><b>Área</b></td>
                <td colspan="2"><%= @activity.work_flow.work_area.name %></td>
                <td colspan="2"><b>Proceso</b></td>
                <td colspan="4"><%= @activity.work_flow.name%></td>
            </tr>
            
            <tr>
                
                <td><b>Actividad</b></td>
                <td colspan="2"><%= @activity.description%></td>
                <td colspan="2"><b>Tarea Unitaria</b></td>
                <td colspan="4"><%= @unitary_task.description %></td>
            </tr>
            <tr>
                <th rowspan="2">Peligro</th>
                <th rowspan="2">Riesgo</th>
                <th colspan="2">Causa Básica</th>
                <th rowspan="2">Probabilidad</th>
                <th rowspan="2">Consecuencia</th>   
                <th rowspan="2">Magnitud</th>
                <th rowspan="2">Calificación</th>
                <th rowspan="2">Procedimiento</th>
            </tr>
            <tr>
                <th>Factor Personal</th>
                <th>Factor Trabajo</th>  
            </tr>


        <% @risk_matrix.each do |rm|%>
        <tr>
            <td><%= rm.risk.danger.description %></td>
            <td><%= rm.risk.description%></td>
            <td><%= rm.personal_cause %></td>
            <td><%= rm.work_cause %></td>
            <td align="center"><%= rm.probability %></td>
            <% if rm.consequence == @consecuencia.last.value %>
                <td align="center" bgcolor="#FF0000"><%= rm.consequence%></td> 
             <%else%>      
                <td align="center"><%= rm.consequence%></td> 
             <%end%>
            
            <td align="center"><%= rm.magnitude%></td>
            <% if @r.count == 3 %>
                <% if rm.consequence == @consecuencia.last.value %>
                   <td bgcolor="#FF0000" align="center">Intolerable</td>
                   <% if PreventiveProcedure.where(:risk_matrix_id => rm.id).count == 0 %>
                    <td><%= link_to 'Generar Procedimiento', generar_procedimiento_path(rm.id), :class => "btn btn-mini btn-warning"%></td>
                    <%else%>
                    <td><%= link_to 'Ver Procedimiento', ver_procedimiento_path(rm.id), :class => "btn btn-mini btn-success"%></td>
                    <%end%>
                <% else %>
                    <% if rm.rating == "Intolerable"%>
                        <% if PreventiveProcedure.where(:risk_matrix_id => rm.id).count == 0 %>
                        <td><%= link_to 'Generar Procedimiento', generar_procedimiento_path(rm.id), :class => "btn btn-mini btn-warning"%></td>
                        <%else%>
                            <td><%= link_to 'Ver Procedimiento', ver_procedimiento_path(rm.id), :class => "btn btn-mini btn-success"%></td>
                        <%end%>
                    <% elsif rm.rating == "Tolerable"%>
                         <td bgcolor="#37DA2B" align="center">Tolerable</td>
                         <td></td>
                    <% elsif rm.rating == "Moderado"%>
                        <td bgcolor="#E8F809" align="center">Moderado</td>
                        <td></td>
                    <% end%> 
                <% end %>   
            <% elsif @r.count == 5 %>
                <% if rm.consequence == @consecuencia.last.value %>
                    <td bgcolor="#FF0000" align="center">Intolerable</td>
                    <% if PreventiveProcedure.where(:risk_matrix_id => rm.id).count == 0 %>
                    <td><%= link_to 'Generar Procedimiento', generar_procedimiento_path(rm.id), :class => "btn btn-mini btn-warning"%></td>
                    <%else%>
                        <td><%= link_to 'Ver Procedimiento', ver_procedimiento_path(rm.id), :class => "btn btn-mini btn-success"%></td>
                    <%end%>
                <% else %>                           
                    <% if rm.rating == "Intolerable"%>
                        <td bgcolor="#FF0000" align="center">Intolerable</td>
                        <% if PreventiveProcedure.where(:risk_matrix_id => rm.id).count == 0 %>
                            <td><%= link_to 'Generar Procedimiento', generar_procedimiento_path(rm.id), :class => "btn btn-mini btn-warning"%></td>
                        <%else%>
                            <td><%= link_to 'Ver Procedimiento', ver_procedimiento_path(rm.id), :class => "btn btn-mini btn-success"%></td>
                        <%end%>
                    <% elsif rm.rating == "Tolerable"%>
                         <td bgcolor="#37DA2B" align="center">Tolerable</td>
                         <td></td>
                    <% elsif rm.rating == "Moderado"%>
                        <td bgcolor="#E8F809" align="center">Moderado</td>
                        <td></td>
                    <% end%> 
                <%end%>
            <% elsif @r.count == 7 %>
                <% if rm.consequence == @consecuencia.last.value %>
                    <td bgcolor="#FF0000" align="center">Intolerable</td>
                    <% if PreventiveProcedure.where(:risk_matrix_id => rm.id).count == 0 %>
                    <td><%= link_to 'Generar Procedimiento', generar_procedimiento_path(rm.id), :class => "btn btn-mini btn-warning"%></td>
                    <%else%>
                        <td><%= link_to 'Ver Procedimiento', ver_procedimiento_path(rm.id), :class => "btn btn-mini btn-success"%></td>
                    <%end%>
                <% else %> 
                    <% if rm.rating == "Intolerable"%>
                        <td bgcolor="#FF0000" align="center">Intolerable</td>
                        <% if PreventiveProcedure.where(:risk_matrix_id => rm.id).count == 0 %>
                            <td><%= link_to 'Generar Procedimiento', generar_procedimiento_path(rm.id), :class => "btn btn-mini btn-warning"%></td>
                        <%else%>
                            td><%= link_to 'Ver Procedimiento', ver_procedimiento_path(rm.id), :class => "btn btn-mini btn-success"%></td>
                        <%end%>
                    <% elsif rm.rating == "Tolerable"%>
                        <td bgcolor="#37DA2B" align="center">Tolerable</td>
                        <td></td>
                    <% elsif rm.rating == "Moderado"%>
                        <td bgcolor="#E8F809" align="center">Moderado</td>
                        <td></td>
                    <% end%> 
                <%end%>
            <% end %>
          
        </tr>
        <%end%> <!-- fin ciclo -->
    </table>
</center>
</br>
<center>
    <%= link_to "Exportar a (PDF)", matrix_header_path(@header, format: "pdf"), :class => "active class btn btn-warning" %>
     | <%= link_to 'Actualizar Riesgos',actualizar_riesgo_evaluado_path(@header.id), :class => "btn btn-info" %>
     | <%= link_to ' Atrás' ,activity_unitary_task_path(@activity, @unitary_task.id), :class => "icon-arrow-left btn" %>
</center>