config/routes.rb
YoPrevengo::Application.routes.draw do
  
  resources :users
  resources :user_sessions
  resources :user_types

  resources :matrix_headers
  resources :risk_matrices   
  resources :preventive_procedures  
  resources :risks_damages
  resources :criteria_types
  resources :activity_types
  resources :damages

  resources :companies do
    resources :work_areas  
    resources :evaluation_criteries
  end  

  resources :work_areas do 
      resources :work_flows
  end   

  resources :work_flows do 
    resources :activities
  end

  resources :activities do
    resources :unitary_tasks
  end

  resources :dangers do
    resources :risks
  end 
  
  
  get "welcome/index"

  match 'listar' => 'unitary_tasks#list', as: :listar

  match 'login' => 'user_sessions#new', as: :login
  match 'logout' => 'user_sessions#destroy', as: :logout
  match 'asignarRol/:id' => 'users#asignarRol', :as => :asignarRol

  match 'new_matriz/:id' => 'matrix_headers#new_matriz', as: :new_matriz
  match 'borrar_cabecera/:id' => 'matrix_headers#borrar_cabecera', as: :borrar_cabecera
  match 'generar_nueva_matriz/:id' => 'risk_matrices#generar_nueva_matriz', as: :generar_nueva_matriz

  match 'asignar/:id/asignar' => 'matrix_headers#asignar', as: :asignar
  match 'quitar_riesgo/:id/' => 'matrix_headers#quitar_riesgo', as: :quitar_riesgo

  match 'generar_matriz/:id' => 'risk_matrices#generar_matriz', as: :generar_matriz  
  match 'actualizar_riesgo_evaluado/:id' => 'risk_matrices#actualizar_riesgo_evaluado', as: :actualizar_riesgo_evaluado
  match 'ver_matriz/:id' => 'risk_matrices#ver_matriz', as: :ver_matriz

  match 'generar_procedimiento/:id' => 'preventive_procedures#generar_procedimiento', as: :generar_procedimiento
  match 'ver_procedimiento/:id' => 'preventive_procedures#ver_procedimiento', as: :ver_procedimiento
  match 'actualizar_procedimiento/:id' => 'preventive_procedures#actualizar_procedimiento', as: :actualizar_procedimiento

  match 'users/:id/actualizar_datos' => 'users#actualizar_datos', as: :actualizar_datos
  match 'editarpassword/:id/edit_password' => 'users#edit_password', as: :edit_password
  match 'update_password/:id' => 'users#update_password', as: :update_password

  root :to => 'welcome#index'
  

  match ':controller(/:action(/:id))(.:format)'
end

app/models/activity.rb
class Activity < ActiveRecord::Base
	attr_accessible :description, :work_flow_id, :activity_type_id
	
	# Relaciones
	belongs_to :work_flow
	belongs_to :activity_type
	has_many :unitary_tasks, :dependent => :destroy

	# Validaciones
	# Descripcion de la actividad
	validates 	:description, :presence => { :message => "Debe ingresar una actividad" }

end

app/models/activity_type.rb
class ActivityType < ActiveRecord::Base
	attr_accessible :name
	
	# Relaciones
	has_many :activities

	# Validaciones
	# Nombre
 	validates   :name,
 				:presence => true,
 				:length => {:minimum => 1, :maximum => 254}
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all
    @tipos = ActivityType.where(:activity_id => params[:id])
    @work_flow = WorkFlow.find(params[:work_flow_id])
    @work_area = WorkArea.find(@work_flow.work_area_id)


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @activities }
    end
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
    @unitarytask = UnitaryTask.where(:activity_id => params[:id])
    @activity = Activity.find(params[:id])
    @work_flow = WorkFlow.find(params[:work_flow_id])
    @work_area = WorkArea.find(@work_flow.work_area_id)
    @activities = ActivityType.all

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @activity }
    end
  end

  # GET /activities/new
  # GET /activities/new.json
  def new
    @boton = "Agregar"
    @activities = ActivityType.all
    @activity = Activity.new
    @work_flow = WorkFlow.find(params[:work_flow_id])
    @work_area = WorkArea.find(@work_flow.work_area_id)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @activity }
    end
  end

  # GET /activities/1/edit
  def edit
    @boton = "Actualizar"
    @activities = ActivityType.all
    @activity = Activity.find(params[:id])
    @work_flow = WorkFlow.find(params[:work_flow_id])
    @work_area = WorkArea.find(@work_flow.work_area_id)
  end

  # POST /activities
  # POST /activities.json
  def create
    @activities = ActivityType.all
    @work_flow = WorkFlow.find(params[:work_flow_id])
    @activity = @work_flow.activities.new(params[:activity])
    @work_area = WorkArea.find(@work_flow.work_area_id)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to [@work_area, @work_flow], notice: 'se creo exitosamente.' }
        format.json { render json: @activity, status: :created, location: @activity }
      else
        format.html { render action: "new" }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /activities/1
  # PUT /activities/1.json
  def update
    @activities = ActivityType.all
    @activity = Activity.find(params[:id])
    @work_flow = WorkFlow.find(params[:work_flow_id])

    respond_to do |format|
      if @activity.update_attributes(params[:activity])
        format.html { redirect_to [@work_flow, @activity], notice: 'se modifico exitosamente.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity = Activity.find(params[:id])
    @work_flow = WorkFlow.find(params[:work_flow_id])
    @work_area = WorkArea.find(@work_flow.work_area_id)
    @activity.destroy

    respond_to do |format|
      format.html { redirect_to [@work_area, @work_flow] }
      format.json { head :no_content }
    end
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.erb
<div class="well">  
  <%= simple_form_for [@work_flow, @activity] do |f| %>
    <% if @activity.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

        <ul>
        <% @activity.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :'Nombre de la Actividad' %><br />
      <%= f.text_field :description, :class => "input-medium search-query", style: "width:350px" %>
    </div>
    <div class="field">
      <%= f.label :'Tipo de Actividad' %><br />
      <select name="activity[activity_type_id]">
        <% @activities.each do |tipo| %>
        <option value="<%= tipo.id %>">
          <%= tipo.name %>
        </option> 
        <% end %>
      </select>
    </div>
    

    <div class="modal-footer">
      <center>
        <% if @boton == 'Agregar'%>
          <div class="actions">
            <button type="submit" class="btn btn-success">
              <i class="icon-ok"> Agregar</i>
            </button>
            <i>
              <%= link_to ' Atras', work_area_work_flow_path(@work_area.id, @work_flow.id), :class => "icon-arrow-left btn" %>
            </i>
        <% else %>    
          <div class="actions">
            <button type="submit" class="btn btn-warning"> 
              <i class="icon-refresh"> Actualizar</i>
            </button>
            <button class="btn" data-dismiss="modal" aria-hidden="true">Cancelar</button>
        <% end %>
      </center>
    </div>
   
  <% end %>

</div>

app/views/activities/edit.html.erb
<h3 align="center">Actualizando actividad</h3>

<%= render 'form' %>

<%= link_to 'Atras', work_flow_activity_path(@work_flow.id, @activity.id), :class => "btn btn-warning" %>

app/views/activities/index.html.erb
<h3 align="center">Lista de Actividades</h3>

<table class='table table' >
  <tr>
    <th>ID</th>
    <th>Descripción</th>
    <th>ID de Proceso de Trabajo</th>
    <th>Tipo de Actividad</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @activities.each do |activity| %>
  <tr>
    <td><%= activity.id %></td>
    <td><%= activity.description %></td>
    <td><%= activity.work_flow_id %></td>
    <td><%= activity.activity_type_id %></td>
    <td><%= link_to 'ver', work_flow_activity_path(@work_flow, activity.id) %></td>
    <td><%= link_to 'Editar', edit_work_flow_activity_path(@work_flow, activity) %></td>
    <td><%= link_to 'Eliminar', work_flow_activity_path(@work_flow, activity), confirm: 'Esta seguro?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nueva Actividad', new_work_flow_activity_path %>

app/views/activities/new.html.erb
<h3 align="center">Agregar Actividad</h3>

<%= render 'form' %>
<!--
<%= link_to 'Atras', work_area_work_flow_path(@work_area.id, @work_flow.id), :class => "btn btn-warning" %>
-->

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<div class="well span3" id="divtabla3">

  <p>
    <b><h4 align="center">Datos de la Actividad</h4></b>
  </p>

  <p>
    <b>Compañía:</b>
    <%= @activity.work_flow.work_area.company.name %>
  </p>

  <p>
    <b>Área de Trabajo:</b>
    <%= @activity.work_flow.work_area.name %>
  </p>

  <p>
    <b>Proceso de Trabajo:</b>
    <%= @activity.work_flow.name %>
  </p>

  <p>
    <b>Actividad:</b>
    <%= @activity.description %>
  </p>

  <p>
    <b>Tipo de Actividad:</b>
    <%=@activity.activity_type.name %>
  </p>
  <!--
  <%= link_to 'Actualizar Actividad', edit_work_flow_activity_path(@work_flow, @activity), :class => "btn btn-info" %>
  -->

  <div>
    <a href="#myModal" role="button" class="icon-refresh btn btn-warning" data-toggle="modal"> Actualizar Actividad</a>
    <div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Actualizar Actividad</h3>
      </div>
      <div class="modal-body">
        <p>
          <%= render 'form' %>
        </p>
      </div>
    </div>
     | <%= link_to ' Atras', work_area_work_flow_path(@work_area.id, @activity.work_flow_id), :class => "icon-arrow-left btn" %>
  </div>


</div>
</br></br>
<div class="well span6" id="divtabla421">
          <p>
            <b><h4 align="center">Listado de Tarea Unitarias</h4></b>
          </p>
          <table class='table'>
            <tr>
              <th>Tarea Unitarias</th>
              <th></th>
            </tr>

           <% @unitarytask.each do |ut| %>
              <tr>
                
                <td><%= link_to ut.description, activity_unitary_task_path(@activity, ut.id) %>
                <td width="100"><%= link_to ' Eliminar', activity_unitary_task_path(@activity, ut.id), confirm: "¿Esta seguro que desea eliminar la tarea unitaria: #{ut.description}", method: :delete, :class => "active icon-trash btn btn-mini btn-danger" %></td>
              </tr>
            <% end %>
          </table>
          </br><%= link_to ' Agregar Tarea Unitaria', new_activity_unitary_task_path(@activity.id), :class => "active icon-pencil btn btn-success" %>
</div>


<!--
<p>
  <b>Tareas Unitarias:</b>
  </br><%= link_to 'Agregar nueva Tarea Unitaria', new_activity_unitary_task_path(@activity.id), :class => "btn btn-info" %>
  <ul>
  	<% @unitarytask.each do |ut| %>
  		<li>
  			<%= link_to ut.description, activity_unitary_task_path(@activity, ut.id) %>
        <%= link_to 'Eliminar', activity_unitary_task_path(@activity, ut.id), confirm: "¿Esta seguro que desea eliminar la tarea unitaria: #{ut.description}", method: :delete, :class => "btn btn-warning" %>
  		</li>
  	<% end %>
  </ul>
</p>
<%= link_to 'Atras', work_area_work_flow_path(@work_area.id, @activity.work_flow_id), :class => "btn btn-warning" %>
-->